name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16.3]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.1.0
      - name: npm install, build
        run: |
          npm install
          npm run build
          firebase login --token "$FIREBASE_TOKEN"
          firebase deploy --token "$FIREBASE_TOKEN"
        env:
          CI: false
